- hosts: all
  tasks:

  - name: Remote RPM
    yum: name=https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Install MySql
    yum:
      name:
        - mysql-server
        - mysql-devel
      state: present
