- hosts: all
  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Install nginx
    yum:
      name:
        - mysql-server
        - mysql-devel
      state: present
