- hosts: all
  tasks:
  - name: yum update & upgrade
    yum:
      name: '*'
      state: latest

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Install MySql
    yum:
      name:
        - mysql-server
        - mysql-devel
      state: present
