- hosts: mysql-server
  tasks:
  - name: yum install htop1
    yum:
      name: htop
      state: latest
  - name: Remote RPM
    yum: name=https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm


  - name: Ensure required packages are Installed
    dnf:
     name:
      - mysql-server
      - mysql-devel
      - gcc
     disable_gpg_check: yes
     state: latest
  - name: Ensure mysql service is running
    systemd:
     name: mysqld
     state: started
     enabled: yes

  - mysql_user:
    name: ''
    host: localhost
    state: absent

# Removes all anonymous user accounts
- mysql_user:
    name: ''
    host_all: yes
    state: absent

- mysql_user:
    name: root
    password: sdfj67856sd;fljsdf98335
    priv: '*.*:ALL'
    host: localhost
    state: present




# create mysql db
- mysql_db:
    community.mysql.mysql_db:
     name: webx
     state: present
     
- mysql_user:
    name: webx
    password: sdfj67856sd;fljsdf98335
    priv: '*webx*:ALL,GRANT'
    host: localhost
    state: present
