- hosts: all
  tasks:
  - name: yum install htop
    yum:
      name: htop
      state: latest
  - name: Remote RPM
    yum: name=https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Ensure required packages are Installed
    dnf:
     name:
      - mysql-server
      - mysql-devel
      - gcc
     disable_gpg_check: yes
     state: latest
