- name: Hots
  hosts: all
  become: yes

  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: install htop
    yum:
      name: htop
      state: latest

  - name: Install Mysql
    yum:
      name:
        - mysql-devel
        - mysql-server

      state: latest
