- hosts: mysql-server

  tasks:
#  - name: yum install htop
#    yum:
#      name: htop
#      state: latest
#  - name: Remote RPM
#    yum: name=https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
#
  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Ensure nginx service is running
    systemd:
     name: nginx
     state: started
     enabled: yes

  handlers:
   - name: 'Restart nginx service'
     service:
       name: nginx
       state: restarted
       become: true
